#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : qtquickcontrols
Version  : 5.10.1
Release  : 6
URL      : http://download.qt.io/official_releases/qt/5.10/5.10.1/submodules/qtquickcontrols-everywhere-src-5.10.1.tar.xz
Source0  : http://download.qt.io/official_releases/qt/5.10/5.10.1/submodules/qtquickcontrols-everywhere-src-5.10.1.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 GFDL-1.3 GPL-2.0 GPL-3.0 LGPL-3.0 OFL-1.0
Requires: qtquickcontrols-lib
BuildRequires : mesa-dev
BuildRequires : pkgconfig(Qt5Core)
BuildRequires : pkgconfig(Qt5Gui)
BuildRequires : pkgconfig(Qt5Qml)
BuildRequires : pkgconfig(Qt5Quick)
BuildRequires : pkgconfig(Qt5QuickWidgets)
BuildRequires : pkgconfig(Qt5Sql)
BuildRequires : pkgconfig(Qt5Test)
BuildRequires : pkgconfig(Qt5Widgets)
BuildRequires : qtbase-dev
BuildRequires : qtbase-extras

%description
ABOUT
This project aims to deliver widgets/controls functionality with Qt Quick.

%package lib
Summary: lib components for the qtquickcontrols package.
Group: Libraries

%description lib
lib components for the qtquickcontrols package.


%prep
%setup -q -n qtquickcontrols-everywhere-src-5.10.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
qmake QMAKE_CFLAGS="$CFLAGS" QMAKE_CXXFLAGS="$CXXFLAGS" QMAKE_LFLAGS="$LDFLAGS" \
    QMAKE_CFLAGS_RELEASE= QMAKE_CXXFLAGS_RELEASE=
test -r config.log && cat config.log
make  %{?_smp_mflags}

%install
make INSTALL_ROOT=%{buildroot} install

%files
%defattr(-,root,root,-)

%files lib
%defattr(-,root,root,-)
/usr/lib64/qt5/qml/QtQuick/Controls/ApplicationWindow.qml
/usr/lib64/qt5/qml/QtQuick/Controls/BusyIndicator.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Button.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Calendar.qml
/usr/lib64/qt5/qml/QtQuick/Controls/CheckBox.qml
/usr/lib64/qt5/qml/QtQuick/Controls/ComboBox.qml
/usr/lib64/qt5/qml/QtQuick/Controls/GroupBox.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Label.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Menu.qml
/usr/lib64/qt5/qml/QtQuick/Controls/MenuBar.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Private/AbstractCheckable.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Private/BasicButton.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Private/BasicTableView.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Private/CalendarHeaderModel.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Private/CalendarUtils.js
/usr/lib64/qt5/qml/QtQuick/Controls/Private/ColumnMenuContent.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Private/ContentItem.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Private/Control.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Private/EditMenu.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Private/EditMenu_base.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Private/FastGlow.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Private/FocusFrame.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Private/HoverButton.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Private/MenuContentItem.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Private/MenuContentScroller.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Private/MenuItemSubControls.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Private/ModalPopupBehavior.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Private/ScrollBar.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Private/ScrollViewHelper.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Private/SourceProxy.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Private/StackView.js
/usr/lib64/qt5/qml/QtQuick/Controls/Private/StackViewSlideDelegate.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Private/Style.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Private/SystemPaletteSingleton.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Private/TabBar.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Private/TableViewItemDelegateLoader.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Private/TableViewSelection.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Private/TextHandle.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Private/TextInputWithHandles.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Private/TextSingleton.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Private/ToolMenuButton.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Private/TreeViewItemDelegateLoader.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Private/qmldir
/usr/lib64/qt5/qml/QtQuick/Controls/Private/style.js
/usr/lib64/qt5/qml/QtQuick/Controls/ProgressBar.qml
/usr/lib64/qt5/qml/QtQuick/Controls/RadioButton.qml
/usr/lib64/qt5/qml/QtQuick/Controls/ScrollView.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Slider.qml
/usr/lib64/qt5/qml/QtQuick/Controls/SpinBox.qml
/usr/lib64/qt5/qml/QtQuick/Controls/SplitView.qml
/usr/lib64/qt5/qml/QtQuick/Controls/StackView.qml
/usr/lib64/qt5/qml/QtQuick/Controls/StackViewDelegate.qml
/usr/lib64/qt5/qml/QtQuick/Controls/StackViewTransition.qml
/usr/lib64/qt5/qml/QtQuick/Controls/StatusBar.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/ApplicationWindowStyle.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/BasicTableViewStyle.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/BusyIndicatorStyle.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/ButtonStyle.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/CalendarStyle.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/CheckBoxStyle.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/CircularButtonStyle.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/CircularGaugeStyle.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/CircularTickmarkLabelStyle.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/ComboBoxStyle.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/CommonStyleHelper.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/DelayButtonStyle.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/DialStyle.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/FocusFrameStyle.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/GaugeStyle.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/GroupBoxStyle.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/HandleStyle.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/HandleStyleHelper.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/MenuBarStyle.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/MenuStyle.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/PieMenuStyle.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/ProgressBarStyle.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/RadioButtonStyle.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/ScrollViewStyle.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/SliderStyle.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/SpinBoxStyle.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/StatusBarStyle.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/StatusIndicatorStyle.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/SwitchStyle.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/TabViewStyle.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/TableViewStyle.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/TextAreaStyle.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/TextFieldStyle.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/ToggleButtonStyle.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/ToolBarStyle.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/ToolButtonStyle.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/TreeViewStyle.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/TumblerStyle.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/images/arrow-down.png
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/images/arrow-down@2x.png
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/images/arrow-left.png
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/images/arrow-left@2x.png
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/images/arrow-right.png
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/images/arrow-right@2x.png
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/images/arrow-up.png
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/images/arrow-up@2x.png
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/images/button.png
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/images/button_down.png
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/images/check.png
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/images/check@2x.png
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/images/editbox.png
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/images/focusframe.png
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/images/groupbox.png
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/images/header.png
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/images/knob.png
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/images/leftanglearrow.png
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/images/needle.png
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/images/progress-indeterminate.png
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/images/rightanglearrow.png
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/images/scrollbar-handle-horizontal.png
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/images/scrollbar-handle-transient.png
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/images/scrollbar-handle-vertical.png
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/images/slider-groove.png
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/images/slider-handle.png
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/images/spinner_large.png
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/images/spinner_medium.png
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/images/spinner_small.png
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/images/tab.png
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Base/images/tab_selected.png
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Desktop/ApplicationWindowStyle.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Desktop/BusyIndicatorStyle.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Desktop/ButtonStyle.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Desktop/CalendarStyle.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Desktop/CheckBoxStyle.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Desktop/ComboBoxStyle.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Desktop/FocusFrameStyle.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Desktop/GroupBoxStyle.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Desktop/MenuBarStyle.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Desktop/MenuStyle.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Desktop/ProgressBarStyle.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Desktop/RadioButtonStyle.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Desktop/RowItemSingleton.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Desktop/ScrollViewStyle.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Desktop/SliderStyle.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Desktop/SpinBoxStyle.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Desktop/StatusBarStyle.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Desktop/SwitchStyle.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Desktop/TabViewStyle.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Desktop/TableViewStyle.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Desktop/TextAreaStyle.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Desktop/TextFieldStyle.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Desktop/ToolBarStyle.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Desktop/ToolButtonStyle.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Desktop/TreeViewStyle.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Desktop/qmldir
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Flat/libqtquickextrasflatplugin.so
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/Flat/qmldir
/usr/lib64/qt5/qml/QtQuick/Controls/Styles/qmldir
/usr/lib64/qt5/qml/QtQuick/Controls/Switch.qml
/usr/lib64/qt5/qml/QtQuick/Controls/Tab.qml
/usr/lib64/qt5/qml/QtQuick/Controls/TabView.qml
/usr/lib64/qt5/qml/QtQuick/Controls/TableView.qml
/usr/lib64/qt5/qml/QtQuick/Controls/TableViewColumn.qml
/usr/lib64/qt5/qml/QtQuick/Controls/TextArea.qml
/usr/lib64/qt5/qml/QtQuick/Controls/TextField.qml
/usr/lib64/qt5/qml/QtQuick/Controls/ToolBar.qml
/usr/lib64/qt5/qml/QtQuick/Controls/ToolButton.qml
/usr/lib64/qt5/qml/QtQuick/Controls/TreeView.qml
/usr/lib64/qt5/qml/QtQuick/Controls/libqtquickcontrolsplugin.so
/usr/lib64/qt5/qml/QtQuick/Controls/plugins.qmltypes
/usr/lib64/qt5/qml/QtQuick/Controls/qmldir
/usr/lib64/qt5/qml/QtQuick/Dialogs/DefaultColorDialog.qml
/usr/lib64/qt5/qml/QtQuick/Dialogs/DefaultDialogWrapper.qml
/usr/lib64/qt5/qml/QtQuick/Dialogs/DefaultFileDialog.qml
/usr/lib64/qt5/qml/QtQuick/Dialogs/DefaultFontDialog.qml
/usr/lib64/qt5/qml/QtQuick/Dialogs/DefaultMessageDialog.qml
/usr/lib64/qt5/qml/QtQuick/Dialogs/Private/libdialogsprivateplugin.so
/usr/lib64/qt5/qml/QtQuick/Dialogs/Private/plugins.qmltypes
/usr/lib64/qt5/qml/QtQuick/Dialogs/Private/qmldir
/usr/lib64/qt5/qml/QtQuick/Dialogs/WidgetColorDialog.qml
/usr/lib64/qt5/qml/QtQuick/Dialogs/WidgetFileDialog.qml
/usr/lib64/qt5/qml/QtQuick/Dialogs/WidgetFontDialog.qml
/usr/lib64/qt5/qml/QtQuick/Dialogs/WidgetMessageDialog.qml
/usr/lib64/qt5/qml/QtQuick/Dialogs/images/checkers.png
/usr/lib64/qt5/qml/QtQuick/Dialogs/images/checkmark.png
/usr/lib64/qt5/qml/QtQuick/Dialogs/images/copy.png
/usr/lib64/qt5/qml/QtQuick/Dialogs/images/critical.png
/usr/lib64/qt5/qml/QtQuick/Dialogs/images/crosshairs.png
/usr/lib64/qt5/qml/QtQuick/Dialogs/images/information.png
/usr/lib64/qt5/qml/QtQuick/Dialogs/images/question.png
/usr/lib64/qt5/qml/QtQuick/Dialogs/images/slider_handle.png
/usr/lib64/qt5/qml/QtQuick/Dialogs/images/sunken_frame.png
/usr/lib64/qt5/qml/QtQuick/Dialogs/images/warning.png
/usr/lib64/qt5/qml/QtQuick/Dialogs/images/window_border.png
/usr/lib64/qt5/qml/QtQuick/Dialogs/libdialogplugin.so
/usr/lib64/qt5/qml/QtQuick/Dialogs/plugins.qmltypes
/usr/lib64/qt5/qml/QtQuick/Dialogs/qml/ColorSlider.qml
/usr/lib64/qt5/qml/QtQuick/Dialogs/qml/DefaultWindowDecoration.qml
/usr/lib64/qt5/qml/QtQuick/Dialogs/qml/IconButtonStyle.qml
/usr/lib64/qt5/qml/QtQuick/Dialogs/qml/IconGlyph.qml
/usr/lib64/qt5/qml/QtQuick/Dialogs/qml/icons.ttf
/usr/lib64/qt5/qml/QtQuick/Dialogs/qml/qmldir
/usr/lib64/qt5/qml/QtQuick/Dialogs/qmldir
/usr/lib64/qt5/qml/QtQuick/Extras/CircularGauge.qml
/usr/lib64/qt5/qml/QtQuick/Extras/DelayButton.qml
/usr/lib64/qt5/qml/QtQuick/Extras/Dial.qml
/usr/lib64/qt5/qml/QtQuick/Extras/Gauge.qml
/usr/lib64/qt5/qml/QtQuick/Extras/PieMenu.qml
/usr/lib64/qt5/qml/QtQuick/Extras/Private/CircularButton.qml
/usr/lib64/qt5/qml/QtQuick/Extras/Private/CircularButtonStyleHelper.qml
/usr/lib64/qt5/qml/QtQuick/Extras/Private/CircularTickmarkLabel.qml
/usr/lib64/qt5/qml/QtQuick/Extras/Private/Handle.qml
/usr/lib64/qt5/qml/QtQuick/Extras/Private/PieMenuIcon.qml
/usr/lib64/qt5/qml/QtQuick/Extras/Private/TextSingleton.qml
/usr/lib64/qt5/qml/QtQuick/Extras/Private/qmldir
/usr/lib64/qt5/qml/QtQuick/Extras/StatusIndicator.qml
/usr/lib64/qt5/qml/QtQuick/Extras/ToggleButton.qml
/usr/lib64/qt5/qml/QtQuick/Extras/Tumbler.qml
/usr/lib64/qt5/qml/QtQuick/Extras/TumblerColumn.qml
/usr/lib64/qt5/qml/QtQuick/Extras/designer/CircularGaugeSpecifics.qml
/usr/lib64/qt5/qml/QtQuick/Extras/designer/DelayButtonSpecifics.qml
/usr/lib64/qt5/qml/QtQuick/Extras/designer/DialSpecifics.qml
/usr/lib64/qt5/qml/QtQuick/Extras/designer/GaugeSpecifics.qml
/usr/lib64/qt5/qml/QtQuick/Extras/designer/PictureSpecifics.qml
/usr/lib64/qt5/qml/QtQuick/Extras/designer/PieMenuSpecifics.qml
/usr/lib64/qt5/qml/QtQuick/Extras/designer/StatusIndicatorSpecifics.qml
/usr/lib64/qt5/qml/QtQuick/Extras/designer/ToggleButtonSpecifics.qml
/usr/lib64/qt5/qml/QtQuick/Extras/designer/images/circulargauge-icon.png
/usr/lib64/qt5/qml/QtQuick/Extras/designer/images/circulargauge-icon16.png
/usr/lib64/qt5/qml/QtQuick/Extras/designer/images/delaybutton-icon.png
/usr/lib64/qt5/qml/QtQuick/Extras/designer/images/delaybutton-icon16.png
/usr/lib64/qt5/qml/QtQuick/Extras/designer/images/dial-icon.png
/usr/lib64/qt5/qml/QtQuick/Extras/designer/images/dial-icon16.png
/usr/lib64/qt5/qml/QtQuick/Extras/designer/images/gauge-icon.png
/usr/lib64/qt5/qml/QtQuick/Extras/designer/images/gauge-icon16.png
/usr/lib64/qt5/qml/QtQuick/Extras/designer/images/picture-icon.png
/usr/lib64/qt5/qml/QtQuick/Extras/designer/images/picture-icon16.png
/usr/lib64/qt5/qml/QtQuick/Extras/designer/images/piemenu-icon.png
/usr/lib64/qt5/qml/QtQuick/Extras/designer/images/piemenu-icon16.png
/usr/lib64/qt5/qml/QtQuick/Extras/designer/images/statusindicator-icon.png
/usr/lib64/qt5/qml/QtQuick/Extras/designer/images/statusindicator-icon16.png
/usr/lib64/qt5/qml/QtQuick/Extras/designer/images/togglebutton-icon.png
/usr/lib64/qt5/qml/QtQuick/Extras/designer/images/togglebutton-icon16.png
/usr/lib64/qt5/qml/QtQuick/Extras/designer/images/tumbler-icon.png
/usr/lib64/qt5/qml/QtQuick/Extras/designer/images/tumbler-icon16.png
/usr/lib64/qt5/qml/QtQuick/Extras/designer/qtquickextras.metainfo
/usr/lib64/qt5/qml/QtQuick/Extras/libqtquickextrasplugin.so
/usr/lib64/qt5/qml/QtQuick/Extras/plugins.qmltypes
/usr/lib64/qt5/qml/QtQuick/Extras/qmldir
/usr/lib64/qt5/qml/QtQuick/PrivateWidgets/libwidgetsplugin.so
/usr/lib64/qt5/qml/QtQuick/PrivateWidgets/plugins.qmltypes
/usr/lib64/qt5/qml/QtQuick/PrivateWidgets/qmldir
